root: ./

structure:
  readme: index.md
  summary: SUMMARY.md

redirects:
  index.html: index.md
  00_01_getting_started.html: 00_01_getting_started.md
  01_00_data_integration.html: 01_00_data_integration.md
  01_01_csv_import.html: 01_01_csv_import.md
  01_02_connect_external_system.html: 01_02_connect_external_system.md
  01_02_manual_edit.html: 01_02_manual_edit.md
  01_03_create_from_scratch.html: 01_03_create_from_scratch.md
  01_04_load_with_python.html: 01_04_load_with_python.md
  02_00_modeling.html: 02_00_modeling.md
  02_01_control_panel.html: 02_01_control_panel.md
  03_00_computations.html: 03_00_computations.md
  03_01_formulas.html: 03_01_formulas.md
  03_02_lookup_columns.html: 03_02_lookup_columns.md
  03_03_mapping_columns.html: 03_03_mapping_columns.md
  04_00_visualization.html: 04_00_visualization.md
  04_01_grid_views.html: 04_01_grid_views.md
  04_02_chart_views.html: 04_02_chart_views.md
  04_03_pivot_table_views.html: 04_03_pivot_table_views.md
  04_04_filtering.html: 04_04_filtering.md
  05_00_publishing.html: 05_00_publishing.md
  05_01_reports.html: 05_01_reports.md
  05_02_applications.html: 05_02_applications.md
  06_00_ai_integration.html: 06_00_ai_integration.md
  07_00_workflows.html: 07_00_workflows.md
  07_01_workflows_case1.html: 07_01_workflows_case1.md
  08_00_administration.html: 08_00_administration.md
  08_01_permissions.html: 08_01_permissions.md
  08_02_security.html: 08_02_security.md
  09_00_python_integration.html: 09_00_python_integration.md
  09_01_python_sdk.html: 09_01_python_sdk.md
  09_02_python_tools.html: 09_02_python_tools.md
  09_03_python_tools_case1.html: 09_03_python_tools_case1.md
  10_00_architecture.html: 10_00_architecture.md
  10_01_lakehouse.html: 10_01_lakehouse.md
  10_02_snowflake_native_connector.html: 10_02_snowflake_native_connector.md
  10_03_query_cache.html: 10_03_query_cache.md
  11_00_exploitation.html: 11_00_exploitation.md
  11_01_backup_restore.html: 11_01_backup_restore.md
  11_02_create_monitoring_data.html: 11_02_create_monitoring_data.md
  11_03_oauth2_configuration.html: 11_03_oauth2_configuration.md
  12_00_release_notes.html: 12_00_release_notes.md
  12_01_release_note_1.32.html: 12_01_release_note_1.32.md
  12_02_release_note_1.33.html: 12_02_release_note_1.33.md
  12_03_release_note_1.34.html: 12_03_release_note_1.34.md
  13_00_terminology.html: 13_00_terminology.md
