title: KAWA Reference Documentation
remote_theme: pmarsceill/just-the-docs
plugins:
  - jekyll-remote-theme
url: https://kawa-analytics.github.io
baseurl: ""
favicon_ico: "/favicon.ico"
logo: "logo.png"
