title: KAWA Reference Documentation
remote_theme: <kawa-analytics>/just-the-docs@fullwidth
plugins:
  - jekyll-remote-theme
url: https://kawa-analytics.github.io
baseurl: ""
favicon_ico: "/favicon.ico"
logo: "logo.png"
